version: "3.9"
services:
  tomcat:
    image: tomcat:latest
    container_name: tomcat1
    ports:
      - 8081:8080
    volumes:
      - my_tomcat:/usr/local/tomcat
    networks:
      coffee:
        ipv4_address: 192.168.92.21
    restart: always

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins1
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - my_jenkins:/var/jenkins_home
    networks:
      coffee:
        ipv4_address: 192.168.92.22
    restart: always

volumes:
  my_tomcat: {}
  my_jenkins: {}

networks:
  coffee:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"


